#!/bin/sh
# Seed cordis patches and agent instruction packs into the DSH_HOME volume.
# Backend path: dsh -> LiteLLM -> TensorFold (host :8421 / :8423) with optional oMLX.
# Agent packs: /opt/dsh-patches/agents/public (baked) + optional private mount.
# Run via: ./run-dsh.sh seed
set -e
: "${DSH_HOME:=/data}"
for p in web headless; do
  mkdir -p "$DSH_HOME/profiles/$p"
  cp "/opt/dsh-patches/$p/cordis.patch.yml" "$DSH_HOME/profiles/$p/cordis.patch.yml"
  echo "seeded $DSH_HOME/profiles/$p/cordis.patch.yml"
done

# Build $DSH_HOME/AGENTS.md from numbered packs (dsh loads this single file).
AGENTS_OUT="$DSH_HOME/AGENTS.md"
PUBLIC_DIR="/opt/dsh-patches/agents/public"
PRIVATE_DIR="/opt/dsh-patches/agents/private"
: > "$AGENTS_OUT"
{
  echo "<!-- generated by seed-omlx.sh — edit agents/public and agents/private, then re-seed -->"
  echo
} >> "$AGENTS_OUT"

_pub_n=0
if [ -d "$PUBLIC_DIR" ]; then
  # POSIX: sorted concat of *.md
  for f in "$PUBLIC_DIR"/*.md; do
    [ -f "$f" ] || continue
    echo >> "$AGENTS_OUT"
    cat "$f" >> "$AGENTS_OUT"
    echo >> "$AGENTS_OUT"
    _pub_n=$((_pub_n + 1))
  done
else
  echo "seed warning: missing $PUBLIC_DIR" >&2
fi

_priv_n=0
if [ -d "$PRIVATE_DIR" ]; then
  for f in "$PRIVATE_DIR"/*.md; do
    [ -f "$f" ] || continue
    echo >> "$AGENTS_OUT"
    cat "$f" >> "$AGENTS_OUT"
    echo >> "$AGENTS_OUT"
    _priv_n=$((_priv_n + 1))
  done
fi

echo "seeded $AGENTS_OUT (public packs: $_pub_n, private packs: $_priv_n, lines: $(wc -l < "$AGENTS_OUT"))"

# Writable scratch + package caches on the volume (not the 64MB noexec /tmp).
mkdir -p \
  "${PNPM_HOME:-$DSH_HOME/.pnpm}" \
  "$DSH_HOME/tmp" \
  "$DSH_HOME/.npm" \
  "$DSH_HOME/cache"

# Default model: smart-router -> TensorFold. Saved settings.yaml overrides cordis.
cat > "$DSH_HOME/settings.yaml" << 'SEOF'
ui-onboarding:
  welcomeNoticeVersion: 2026-08-13.1
agent-default-model:
  provider: deepseek-official
  model: smart-router
  reasoningEffort: high
SEOF

# Web profile: ensure local git-branch-dock plugin (composer footer branch).
_PLUGIN_SRC="/opt/dsh-plugins/dsh-git-branch-dock"
_WEB_PKG="$DSH_HOME/profiles/web/package.json"
if [ -d "$_PLUGIN_SRC" ] && [ -f "$_WEB_PKG" ]; then
  if ! grep -q '"dsh-git-branch-dock"' "$_WEB_PKG" 2>/dev/null; then
    echo "seeding dsh-git-branch-dock into web profile…"
    # Prefer dsh plugin CLI when available; fall back to package.json edit + pnpm.
    if command -v dsh >/dev/null 2>&1; then
      dsh plugin --profile web add "$_PLUGIN_SRC" \
        || dsh plugin --profile web add "$_PLUGIN_SRC" --config.ignore-scripts=false \
        || echo "seed warning: dsh plugin add dsh-git-branch-dock failed" >&2
    fi
  fi
  # Ensure bundle list includes the plugin so the host + client load.
  if command -v node >/dev/null 2>&1; then
    WEB_PKG="$_WEB_PKG" node - <<'NODE' || true
const fs = require('fs');
const p = process.env.WEB_PKG;
const j = JSON.parse(fs.readFileSync(p, 'utf8'));
j.dsh = j.dsh || {};
j.dsh.profile = j.dsh.profile || {};
j.dsh.profile.bundles = j.dsh.profile.bundles || [];
if (!j.dsh.profile.bundles.includes('dsh-git-branch-dock')) {
  j.dsh.profile.bundles.push('dsh-git-branch-dock');
}
j.dependencies = j.dependencies || {};
if (!j.dependencies['dsh-git-branch-dock']) {
  j.dependencies['dsh-git-branch-dock'] = 'file:/opt/dsh-plugins/dsh-git-branch-dock';
}
fs.writeFileSync(p, JSON.stringify(j, null, 2) + '\n');
NODE
    (cd "$DSH_HOME/profiles/web" && pnpm install --config.ignore-scripts=true) \
      || echo "seed warning: pnpm install for git-branch-dock failed" >&2
  fi
fi

echo "TensorFold/oMLX patches + agent packs + pnpm store + default model ready."
