#!/bin/sh
# Seed cordis patches and agent instruction packs into the DSH_HOME volume.
# Backend path: dsh -> LiteLLM -> TensorFold (host :8421 / :8423) with optional oMLX.
# Agent packs: /opt/dsh-patches/agents/public (baked) + optional private mount.
# Run via: ./run-dsh.sh seed
set -e
: "${DSH_HOME:=/data}"
for p in web headless; do
  mkdir -p "$DSH_HOME/profiles/$p"
  cp "/opt/dsh-patches/$p/cordis.patch.yml" "$DSH_HOME/profiles/$p/cordis.patch.yml"
  echo "seeded $DSH_HOME/profiles/$p/cordis.patch.yml"
done

# Build $DSH_HOME/AGENTS.md from numbered packs (dsh loads this single file).
AGENTS_OUT="$DSH_HOME/AGENTS.md"
PUBLIC_DIR="/opt/dsh-patches/agents/public"
PRIVATE_DIR="/opt/dsh-patches/agents/private"
: > "$AGENTS_OUT"
{
  echo "<!-- generated by seed-omlx.sh — edit agents/public and agents/private, then re-seed -->"
  echo
} >> "$AGENTS_OUT"

_pub_n=0
if [ -d "$PUBLIC_DIR" ]; then
  # POSIX: sorted concat of *.md
  for f in "$PUBLIC_DIR"/*.md; do
    [ -f "$f" ] || continue
    echo >> "$AGENTS_OUT"
    cat "$f" >> "$AGENTS_OUT"
    echo >> "$AGENTS_OUT"
    _pub_n=$((_pub_n + 1))
  done
else
  echo "seed warning: missing $PUBLIC_DIR" >&2
fi

_priv_n=0
if [ -d "$PRIVATE_DIR" ]; then
  for f in "$PRIVATE_DIR"/*.md; do
    [ -f "$f" ] || continue
    echo >> "$AGENTS_OUT"
    cat "$f" >> "$AGENTS_OUT"
    echo >> "$AGENTS_OUT"
    _priv_n=$((_priv_n + 1))
  done
fi

echo "seeded $AGENTS_OUT (public packs: $_pub_n, private packs: $_priv_n, lines: $(wc -l < "$AGENTS_OUT"))"

# Writable scratch + package caches on the volume (not the 64MB noexec /tmp).
mkdir -p \
  "${PNPM_HOME:-$DSH_HOME/.pnpm}" \
  "$DSH_HOME/tmp" \
  "$DSH_HOME/.npm" \
  "$DSH_HOME/cache"

# Default model: smart-router -> TensorFold. Saved settings.yaml overrides cordis.
cat > "$DSH_HOME/settings.yaml" << 'SEOF'
ui-onboarding:
  welcomeNoticeVersion: 2026-08-13.1
agent-default-model:
  provider: deepseek-official
  model: smart-router
  reasoningEffort: high
SEOF
echo "TensorFold/oMLX patches + agent packs + pnpm store + default model ready."
